### ISSUE TITLE
Details?

### ISSUE THREAD

**Issue by vincentyang116** [salhernandez/wired2Bluetooth#1]
Hi,
Could you share the details of this convert, like hardwares and tools?
Thanks.

**Comment by salhernandez** [comment]
The original intent for this project was to create an interface where I could plug in any usb keyboard and then it would be able to either write it to the connected computer or transmit via USB. I only got it to relay basic keys to the computer.

Here is a sketch of how it would be setup: 
![image](https://user-images.githubusercontent.com/15660327/108322576-7b173780-717a-11eb-8df7-27f963985d5c.png)

Hardware used:
1. Regular keyboard
2. [Arduino Leonardo](https://www.amazon.com/gp/product/B008FZJC74/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1)
   1. Connects to Computer and can act as a peripheral, thus allowing for emulating keystrokes
3. [USB HOST SHIELD](https://www.amazon.com/gp/product/B072HPX4N2/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1)
   1. Keyboard connects to the shield.

Input flow: Keyboard -> USB HOST SHIELD -> Arduino Leonardo -> Computer

Hope this helps!

**Comment by vincentyang116** [comment]
Got it, thanks a lot.

**Comment by salhernandez** [comment]
@vincentyang116  More useful resources:
* https://github.com/djnugent/BLE_WASD/blob/master/README.md
* https://www.arduino.cc/en/Main/Arduino_BoardLeonardo
* https://forum.arduino.cc/index.php?topic=479034.0
* https://kraenhansen.dk/2014/10/arduino-project-platform-independent-clipboard/
* https://www.arduino.cc/en/Tutorial/KeyboardController
* https://forum.arduino.cc/index.php?topic=334626.0
* https://www.arduino.cc/en/Guide/ArduinoDue#toc15
* https://www.youtube.com/watch?v=4fw9kY1GwI4&feature=youtu.be
* https://www.youtube.com/watch?v=_v8BHYyAfnU&feature=youtu.be
* https://www.youtube.com/watch?v=sXs7S048eIo&t=24s
